### ISSUE TITLE
Timeline for release

### ISSUE THREAD

**Issue by reynoldscem** [zju3dv/DetectorFreeSfM#1]
Hi,

Thank you for the great work! I was just wondering if you have an approximate timeline for the code release? Further, whether you'll be including weights?

**Comment by hxy-123** [comment]
Hi,

Thanks for your interest in our work! We plan to release the code, including weights and training code, after the paper's acceptance. If things work all the best, the release time is expected before September. Please stay tuned :).

Best, Xingyi

**Comment by reynoldscem** [comment]
That's great - where are you in submission to?

**Comment by hxy-123** [comment]
We are sorry that we cannot provide more information, due to the dual-blind reviewing requirement.

**Comment by jytime** [comment]
Hi Xingyi @hxy-123 , 

May I ask is there any updates? I was hoping to compare my method to DetectorFreeSfM :)
