### ISSUE TITLE
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'

### ISSUE THREAD

**Issue by qian5683** [zju3dv/DetectorFreeSfM#13]
![image](https://github.com/zju3dv/DetectorFreeSfM/assets/42739722/b73e29ac-ba75-470b-ba50-da03b85bab8c)
When I was running the demo, I encountered a problem

**Comment by hxy-123** [comment]
Hi, if you can make sure the pytorch-lightning in your environment is 1.3.5, then please check the version of torchmetrics. It seems that this is due to the incomparable problem between pytorch-lightning and torchmetrics. You can try to re-install torchmetrics by:
```
pip install torchmetrics==0.6.0
```
