### ISSUE TITLE
 No such file or directory: 'DetectorFreeSfM/src/MultiviewMatcher/backbone/S2DNet/checkpoints/s2dnet_weights.pth'

### ISSUE THREAD

**Issue by qian5683** [zju3dv/DetectorFreeSfM#14]
Where can I download this weight？

**Comment by hxy-123** [comment]
The weight of s2dnet should be [automatically downloaded](https://github.com/zju3dv/DetectorFreeSfM/blob/55efcc216f449850d36e95835c454c41c4e71cd4/src/MultiviewMatcher/backbone/S2DNet/s2dnet.py#L118) when first running the code. You can check whether the network connection problem exists in your machine. Alternatively, you can manually download the weight by the [URL shown here](https://github.com/zju3dv/DetectorFreeSfM/blob/55efcc216f449850d36e95835c454c41c4e71cd4/src/MultiviewMatcher/backbone/S2DNet/s2dnet.py#L70) and place it in the required path.
