### ISSUE TITLE
Questions about SfM evaluation

### ISSUE THREAD

**Issue by songjh2020** [zju3dv/DetectorFreeSfM#24]
Thank you very much for your excellent work, which has greatly benefited me。

 but I have encountered some problems when I run this code: “python eval_dataset.py +eth3d_sfm=dfsfm.yaml neuralsfm.NEUSFM_coarse_matcher='loftr_official'”

The error information is as follows：

![screenshot1](https://github.com/zju3dv/DetectorFreeSfM/assets/102972465/682d148a-30fd-4474-83c9-d283f47eb1e9)

I found the  image. It's damaged, which is shown below:

![screenshot2](https://github.com/zju3dv/DetectorFreeSfM/assets/102972465/96e2e7dc-ed57-4c44-aa81-4af4a918cd68)

I'm sure I followed DATASET_PREPARE.md. Thank you very much for your guidance

（I did not encounter this error when I ran "sh scripts/eval_texturepoorsfm_dataset".）

**Comment by hxy-123** [comment]
I think this may be due to the dataset download being broken. You can try to re-download the ETH3D dataset.

**Comment by songjh2020** [comment]
> I think this may be due to the dataset download being broken. You can try to re-download the ETH3D dataset.

Thank you for your answer, I will seriously try. One more thing, I can't seem to find the "supplementary material" mentioned in the article, could you please give me the link？

**Comment by hxy-123** [comment]
We will update the supplementary material on the project page after camera ready revision soon :)
