### ISSUE TITLE
camera.txt

### ISSUE THREAD

**Issue by passenger1366** [zju3dv/DetectorFreeSfM#26]
![d91cf20b5d3c22924c932c3da31db91](https://github.com/zju3dv/DetectorFreeSfM/assets/86765353/60b86ffd-aafe-445b-9f13-725f87d5b6e8)
Congratulations on your great work！ when reconstructing faces with this project, the cameras visualized in COLMAP GUI appear quite large, while they seem more normal in larger scenes. Is it possible to control this size?
![49d8b211961a8314216e24a940a48e5](https://github.com/zju3dv/DetectorFreeSfM/assets/86765353/3d9566eb-3688-4e53-979a-cd3352f4b644)

**Comment by hxy-123** [comment]
The camera size for visualization can be controlled in colmap gui.

**Comment by passenger1366** [comment]
OK I found it in Render——Render options——camera size，thank you ，Congratulations Again！
