### ISSUE TITLE
Question about small angle coverage?

### ISSUE THREAD

**Issue by Osierddr** [zju3dv/DetectorFreeSfM#46]
Thanks for your excellent work!!! I'm encounting a problem with the reconstruction. Hope your could give me some advice.
My dataset is a sparse input with small viewing angle coverage, with is shown below:
![image](https://github.com/zju3dv/DetectorFreeSfM/assets/144309848/72db5660-0e54-4a1b-a6c1-aa8364e2c305)

Using your project, the point cloud result:
![image1](https://github.com/zju3dv/DetectorFreeSfM/assets/144309848/214d2609-34ff-4c46-9321-10a069bdc2e3)
![image2](https://github.com/zju3dv/DetectorFreeSfM/assets/144309848/582d87f1-e676-40ec-9d12-4e05d9a94ae8)

I noticed that the buildings in the centre do not have matching 3D points, can this be improved by modifying some parameters?
Any advice would be of great help to me!

**Comment by hxy-123** [comment]
Hi, for automatic driving scenes, the camera is forward-moving. The default COLMAP parameter setting may not be suitable for this scenario, because COLMAP has parameters to control minimal triangulation angle for stable reconstruction, where points on the building in the image center cannot satisfy these criteria when the camera is forward moving.
<img width="733" alt="image" src="https://github.com/zju3dv/DetectorFreeSfM/assets/54060345/93f932ee-f68e-4721-a47c-b967d164dfbc">
You can try to relax these parameters that control the triangulation angle.

**Comment by Osierddr** [comment]
> Hi, for automatic driving scenes, the camera is forward-moving. The default COLMAP parameter setting may not be suitable for this scenario, because COLMAP has parameters to control minimal triangulation angle for stable reconstruction, where points on the building in the image center cannot satisfy these criteria when the camera is forward moving. <img alt="image" width="733" src="https://private-user-images.githubusercontent.com/54060345/344093568-93f932ee-f68e-4721-a47c-b967d164dfbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDcwNzYsIm5iZiI6MTcyMDAwNjc3NiwicGF0aCI6Ii81NDA2MDM0NS8zNDQwOTM1NjgtOTNmOTMyZWUtZjY4ZS00NzIxLWE0N2MtYjk2N2QxNjRkZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDExMzkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYWJkNTU4MWJkZmRlZThmMzRjY2JlYjU1MDRhZjgyZDU4YjE5ODBhNjJhNTQyODYyNDIzYTViNGEwMGJkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eeYrrVnrzMnJyi4g9ELRKAZaFhdwoBYF4w-DLt8ApwA"> You can try to relax these parameters that control the triangulation angle.

Thanks! It works well!
