### ISSUE TITLE
colmap

### ISSUE THREAD

**Issue by wwj-53** [zju3dv/DetectorFreeSfM#47]
I have installed the original version of colmap. If I install the modified colmap according to your repo, will it affect my original colmap？

**Comment by hxy-123** [comment]
We add a refinement module based on the original colmap without change other interfaces. Therefore, the original performance of colmap will not be changed. Moreover, you can only [build without install](https://github.com/zju3dv/DetectorFreeSfM/blob/main/INSTALL.md) our modified colmap and *export* the built colmap path before running our SfM system. In this way, you can safely keep your original version of colmap.
