### ISSUE TITLE
Train Multiview Matching Refiner

### ISSUE THREAD

**Issue by wwj-53** [zju3dv/DetectorFreeSfM#52]
Is Train Multiview Matching Refiner mandatory to execute? Or is it enough to use pre trained weights？

**Comment by hxy-123** [comment]
No, the training multiview refiner is not mandatory. Actually, we find the trained model can generalize well to different types of data, where we use the same refinement model weight for evaluation on all datasets in the paper's experiments and IMC 2023 competition. We release the training code and data for further follow-up works.

**Comment by wwj-53** [comment]
thank you!
