### ISSUE TITLE
Q about image used in your paper

### ISSUE THREAD

**Issue by TwiceMao** [zju3dv/DetectorFreeSfM#7]
@JiamingSuen 
Thanks for your awesome work!
Is the lunar imagery used in your research paper sourced from a specific dataset, or obtained through other means.
Thx~

**Comment by hxy-123** [comment]
Hi, the sequence of the moon in the demo is taken from [YouTube video](https://www.youtube.com/watch?v=q2sjqmKeM5g), and preprocessed by extracting relevant frames and cropping out the moon car manually.
